CREATE DATABASE DCE_DB;

USE DCE_DB
GO;

CREATE TABLE Customer (
    UserId UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    Username NVARCHAR(30) NOT NULL,
    Email NVARCHAR(20) NOT NULL,
    FirstName NVARCHAR(20) NOT NULL,
    LastName NVARCHAR(20) NULL,
    CreatedOn DATETIME DEFAULT GETDATE(),
    IsActive BIT DEFAULT 1
);

CREATE TABLE Supplier (
    SupplierId UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    SupplierName NVARCHAR(50) NOT NULL,
    CreatedOn DATETIME DEFAULT GETDATE(),
    IsActive BIT DEFAULT 1
);

CREATE TABLE Product (
    ProductId UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    ProductName NVARCHAR(50) NOT NULL,
    UnitPrice DECIMAL(18, 2) NOT NULL,
    SupplierId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Supplier(SupplierId) NOT NULL,
    CreatedOn DATETIME DEFAULT GETDATE(),
    IsActive BIT DEFAULT 1
);

CREATE TABLE [Order] (
    OrderId UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    ProductId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Product(ProductId) NOT NULL,
    OrderStatus INT NULL,
    OrderType INT NULL,
    OrderBy UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Customer(UserId) NOT NULL,
    OrderedOn DATETIME NULL,
    ShippedOn DATETIME NULL,
    IsActive BIT DEFAULT 0
);
